###############################################################################
# Title: Forest Plot for COVID-19 Survival Analysis (SHAP-based HR visualization)
# Author: malinhjartstrom
# Date: 2025-10-19
# Description:
#   This script reads hazard ratio (HR) summary statistics for binary, continuous,
#   and ordinal predictors from Excel files and constructs a publication-ready
#   forest plot. The plot summarizes HRs, confidence intervals, and p-values
#   across selected clinical variables relevant to COVID-19 survival analysis.
###############################################################################

# Load required libraries ------------------------------------------------------
library(ggplot2)
library(scales)
library(readxl)
library(gridExtra)
library(grid)
library(cowplot)
library(dplyr)
library(ggtext)
library(huxtable)

###############################################################################
# SECTION 1: Load and Prepare Binary Predictors
###############################################################################

# Import binary variable statistics (Excel file generated by SHAP analysis)
binary <- read_excel(
  "SHAP_HR_binary_variables")


# Remove index column (unnamed)
binary_clean <- subset(binary, select = -c(...1))

# Select top binary predictors of interest
binary_top12 <- subset(binary_clean, select = c('DNR order', 'PPI medication', 'ACEi', 'ARB'))

# Create a data frame formatted for plotting
df <- data.frame(
  Variable = paste0("**", colnames(binary_top12), "**"),
  Level = rep_len(c('no vs yes'), length(colnames(binary_top12))),
  logHR_for_sorting = as.numeric(as.vector(binary_top12[1,])),
  HR = as.numeric(as.vector(binary_top12[10,])),
  CI_lower = as.numeric(as.vector(binary_top12[11,])),
  CI_upper = as.numeric(as.vector(binary_top12[12,])),
  p_value = as.numeric(as.vector(binary_top12[16,])),
  N = as.numeric(as.vector(binary_top12[17,]))
)

###############################################################################
# SECTION 2: Add Continuous Predictors
###############################################################################

# Import continuous variable statistics
cont <- read_excel(
  "SHAP_HR_continuous_variables")

cont_clean <- subset(cont, select = -c(...1))

# Select top continuous predictors
cont_top12 <- subset(cont, select = c(
  'Neutrophils', 'Age', '#Days in Hosp. before ICU', 'CFS', 
  'Cystatin C', '#Meds/Patient', 'Albumin', 'BMI', 
  'Leukocytes', 'IL-6'
))

# Define measurement units for labels
cont_units <- c(
  ' (x 10⁹/L)', ' (year)', ' ', ' (level)', ' (mg/L)', ' ', 
  ' (g/L)', ' (kg/m²)', ' (x 10⁹/L)', ' (ng/L)'
)

# Append continuous variables to the main data frame
df <- df %>% add_row(
  Variable = paste0("**", colnames(cont_top12), "**", cont_units),
  Level = c('5 vs 20', '60 vs 75', '4 vs 11', '2 vs 4', '1 vs 3', '2 vs 5', 
            '22 vs 32', '25 vs 35', '5 vs 20', '6 vs 1106'),
  logHR_for_sorting = as.numeric(as.vector(cont_top12[1,])),
  HR = as.numeric(as.vector(cont_top12[10,])),
  CI_lower = as.numeric(as.vector(cont_top12[11,])),
  CI_upper = as.numeric(as.vector(cont_top12[12,])),
  p_value = as.numeric(as.vector(cont_top12[16,])),
  N = as.numeric(as.vector(cont_top12[3,]))
)

###############################################################################
# SECTION 3: Add Ordinal Predictor (CCI)
###############################################################################

# Import Charlson Comorbidity Index (CCI) data
cci <- read_excel(
  "SHAP_HR_ordinal_variables")

ord_cci <- subset(cci, select = -c(...1))

# Add CCI variable
df <- df %>% add_row(
  Variable = paste0("**", c('CCI'), "**", ' (level)'),
  Level = c('3 vs 6'),
  logHR_for_sorting = as.numeric(as.vector(ord_cci[1,12])),
  HR = as.numeric(as.vector(ord_cci[10,12])),
  CI_lower = as.numeric(as.vector(ord_cci[11,12])),
  CI_upper = as.numeric(as.vector(ord_cci[12,12])),
  p_value = as.numeric(as.vector(ord_cci[16,12])),
  N = as.numeric(as.vector(ord_cci[17,12]))
)

# Sort variables by HR
df <- df %>%
  arrange(HR) %>%
  mutate(Variable = factor(Variable, levels = unique(Variable)))

###############################################################################
# SECTION 4: Helper Function for Forest Plot Formatting
###############################################################################

# Function: make_forest_rows
# Description: Formats HR and CI for text display, assigns row indices for plotting
make_forest_rows <- function(df) {
  df %>%
    mutate(
      HR_CI = sprintf("%.2f (%.2f–%.2f)", HR, CI_lower, CI_upper),
      p_val_fmt = format.pval(p_value, digits = 3, eps = .001),
      row_id = row_number()
    )
}

# Apply the function
df_plot <- make_forest_rows(df)
x_range <- range(c(df_plot$CI_lower, df_plot$CI_upper), na.rm = TRUE)

###############################################################################
# SECTION 5: Build Forest Plot Components
###############################################################################

# Variable labels
label_plot <- ggplot(df_plot, aes(y = row_id)) +
  geom_richtext(aes(x = 0, label = Variable), hjust = 0, size = 4.2,
                fill = NA, label.color = NA) +
  theme_void() + xlim(0, 1)

# Comparison level labels
level_plot <- ggplot(df_plot, aes(y = row_id)) +
  geom_text(aes(x = 0, label = Level), hjust = 0, size = 4.2) +
  theme_void() + xlim(0, 1)

# HR and CI text
hr_ci_plot <- ggplot(df_plot, aes(y = row_id)) +
  geom_text(aes(x = 0, label = HR_CI), hjust = 0, size = 4.2) +
  theme_void() + xlim(0, 1)

# P-value text
pval_plot <- ggplot(df_plot, aes(y = row_id)) +
  geom_text(aes(x = 0, label = p_val_fmt), hjust = 0, size = 4.2) +
  theme_void() + xlim(0, 1)

# Forest plot (HR points + CI bars)
forest_plot <- ggplot(df_plot, aes(x = HR, y = row_id)) +
  geom_point(size = 1.5, na.rm = TRUE) +
  geom_errorbarh(aes(xmin = CI_lower, xmax = CI_upper), height = 0.2, na.rm = TRUE) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "gray50") +
  scale_x_log10() +
  coord_cartesian(xlim = x_range) +
  theme_minimal(base_size = 12) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank())

# X-axis for HR
forest_axis <- ggplot(df_plot, aes(x = HR)) +
  geom_blank() +
  scale_x_log10(labels = label_number(accuracy = 0.1)) +
  labs(x = "HR") +
  theme_minimal(base_size = 12) +
  theme(axis.title.x = element_text(margin = margin(t = 15)),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major = element_blank(),
        axis.title.y = element_blank()) +
  coord_cartesian(xlim = x_range)

###############################################################################
# SECTION 6: Combine Panels into Final Forest Plot
###############################################################################

# Title helper function
make_title <- function(label) {
  ggplot() +
    geom_text(aes(x = 0, y = 0, label = label), hjust = 0, size = 5, fontface = "bold") +
    xlim(0, 1) + theme_void()
}

# Define column widths and layout
widths_used <- c(0.52, 0.28, 0.45, 0.40, 0.15)
ncol_used <- 5

# Header row
header_row <- arrangeGrob(
  make_title("Variable"),
  make_title("Level"),
  make_title("Forest plot"),
  make_title("HR (95% CI)"),
  make_title("p-value"),
  ncol = ncol_used,
  widths = widths_used
)

# Body of table (variables + forest plot)
body_row <- arrangeGrob(
  label_plot, level_plot, forest_plot, hr_ci_plot, pval_plot,
  ncol = ncol_used, widths = widths_used
)

# Axis row for HR values
axis_row <- arrangeGrob(
  nullGrob(), nullGrob(), forest_axis, nullGrob(), nullGrob(),
  ncol = ncol_used, widths = widths_used
)

# Combine into final figure
final_plot <- grid.arrange(
  header_row, body_row, axis_row,
  ncol = 1, heights = c(0.08, 1, 0.15)
)

###############################################################################
# SECTION 7: Export Final Plot
###############################################################################

# Save to SVG format for high-quality vector output
svg("c19_survival_forest_plot.svg", width = 11, height = 5)
grid.draw(final_plot)
dev.off()
